### ISSUE TITLE
Confusing org.label-schema.vcs-url

### ISSUE THREAD

**Issue by imjasonh** [rimusz/cloud-builders-helm#2]
First of all, thanks for contributing this builder, and making GCB better!

I was looking through the code and found this in the Dockerfile:

```
      org.label-schema.vcs-url="https://source.developers.google.com/p/serene-craft-154918/r/helm" \
```

What does that label affect? Is this something users should specify themselves, for their own repo?

**Comment by rimusz** [comment]
it does not affect much, I will remove it to have no confusion.
thanks for pointing out

**Comment by imjasonh** [comment]
Oh I see, this marks the repo that this container was built from. That makes sense. I guess it might still be confusing since it's not this GitHub repo, but I don't think that's a big deal.

Thanks again!

**Comment by rimusz** [comment]
remved, and pushed, and image built too :)
